spring:
  application:
    name: aggregator
  datasource:
    url: jdbc:postgresql://localhost:6543/ewm_stats
    username: user
    password: password
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: always
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        format_sql: true
server:
  port: 0

logging:
  level:
    ru.yandex.practicum.aggregator: TRACE
    org:
      springframework: ERROR
      apache.kafka: WARN

aggregator:
  kafka:
    producer:
      properties:
        bootstrap.servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
        key.serializer: org.apache.kafka.common.serialization.StringSerializer
        value.serializer: ru.yandex.practicum.kafka.serializer.GeneralAvroSerializer
      topics:
        - "stats.events-similarity.v1"
    consumer:
      properties:
        bootstrap.servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
        group.id: "stats.aggregator"
        key.deserializer: org.apache.kafka.common.serialization.StringDeserializer
        value.deserializer: ru.yandex.practicum.kafka.deserializer.UserActionAvroDeserializer
        auto.offset.reset: earliest
      topics:
        - "stats.user-actions.v1"
      poll-timeout: 100ms
