services:
  stats-db:
    image: postgres:16.1
    ports:
      - "6542:5432"
    environment:
      POSTGRES_DB: ewm-stats
      POSTGRES_USER: stat
      POSTGRES_PASSWORD: stat

  ewm-db:
    image: postgres:16.1
    ports:
      - "6543:5432"
    environment:
      POSTGRES_DB: ewm-db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
