services:
  postgres:
    image: postgres:16.1
    container_name: postgres-ewm
    hostname: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    ports:
      - "6543:5432"
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      interval: 5s
      retries: 10
      timeout: 5s

  db_init:
    image: postgres:16.1
    container_name: db-init-ewm
    depends_on:
      postgres:
        condition: service_healthy
# Здесь взял за образец то, что было на вебинаре. Пока оставляю
    entrypoint:
      - bash
      - -c
      - |
        set -e
        psql postgresql://user:password@postgres:5432/postgres -v ON_ERROR_STOP=1 <<-EOSQL
          DROP DATABASE IF EXISTS ewm_db;
          DROP DATABASE IF EXISTS ewm_stats;
          DROP DATABASE IF EXISTS user_db;
          DROP DATABASE IF EXISTS request_db; 
          DROP DATABASE IF EXISTS event_db; 
          create database ewm_db;
          create database ewm_stats;
          create database user_db;
          create database request_db;
          create database event_db;
          grant all privileges on database ewm_db to "user";
          grant all privileges on database ewm_stats to "user";
          grant all privileges on database user_db to "user";
          grant all privileges on database request_db to "user";
          grant all privileges on database event_db to "user";
        EOSQL