DROP TABLE IF EXISTS comments;

CREATE TABLE IF NOT EXISTS comments
(
    id       BIGINT      NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id  BIGINT      NOT NULL,
    event_id BIGINT      NOT NULL,
    text     VARCHAR(255) NOT NULL,
    created  TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    status   VARCHAR(15) NOT NULL
-- CONSTRAINT unique_user_event UNIQUE (user_id, event_id)
-- Запрещает вторые комментарии, пока не уверен, что это надо запрещать
);