server:
  port: 8080

spring:
  application:
    name: gateway

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true

      routes:
        - id: main_service_route
          uri: lb://main-service
          predicates:
            - Path=/categories/**,/admin/**,/users/**,/events/**,/compilations/**
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.server.HttpServer: DEBUG