spring:
  config:
    import: "optional:configserver:"
  application:
    name: request-service
    cloud:
      config:
        fail-fast: true
        retry:
          max-attempts: 6
          initial-interval: 2000
          max-interval: 10000
        discovery:
          enabled: true
          service-id: config-server

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname:localhost}:${eureka.instance.port:8761}/eureka/
  instance:
    instance-id: ${spring.application.name}:${random.uuid}
    prefer-ip-address: true
