spring:
  application:
    name: collector
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
server:
  port: 0

grpc:
  server:
    port: 0
  client:
    analytics:
      address: ${GRPC_ANALYTICS_ADDRESS:static://localhost:9091}
      negotiationType: plaintext        # Отключение TLS для локальной отладки

logging:
  level:
    ru.yandex.practicum.collector: TRACE
    org:
      springframework: ERROR
      apache.kafka: WARN

collector:
  kafka:
    producer:
      properties:
        "bootstrap.servers": ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
        "key.serializer": org.apache.kafka.common.serialization.StringSerializer
        "value.serializer": ru.yandex.practicum.kafka.serializer.GeneralAvroSerializer
      topics:
        - "stats.user-actions.v1"
