DROP TABLE IF EXISTS events;
DROP TABLE IF EXISTS locations;

CREATE TABLE IF NOT EXISTS locations (
       id     BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
       lat    decimal,
       lon    decimal
);

CREATE TABLE IF NOT EXISTS events (
  id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title VARCHAR(120) NOT NULL,
  annotation VARCHAR(2000) NOT NULL,
  category_id BIGINT NOT NULL,
  description VARCHAR(7000) NOT NULL,
  event_date TIMESTAMP WITHOUT TIME ZONE,
  location_id BIGINT,
  is_paid boolean,
  participant_limit BIGINT,
  request_moderation boolean,
  creation_date TIMESTAMP WITHOUT TIME ZONE,
  publication_date TIMESTAMP WITHOUT TIME ZONE,
  state VARCHAR(50) NOT NULL,
  views BIGINT,
  initiator_id BIGINT NOT NULL,
  FOREIGN KEY (location_id) REFERENCES locations (id)
);
