spring:
  application:
    name: main-service

  datasource:
    url: jdbc:postgresql://localhost:6543/ewm-db
    username: user
    password: password
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: always
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        format_sql: true

server:
  port: 0

logging:
  level:
    ru.practicum: TRACE
    org:
      springframework: ERROR