DROP TABLE IF EXISTS comments;
DROP TABLE IF EXISTS compilation_events;
DROP TABLE IF EXISTS compilations;
DROP TABLE IF EXISTS category;

CREATE TABLE IF NOT EXISTS category (
       id     BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
       name   VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS compilations
(
    id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pinned boolean,
    title VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS compilation_events
(
    compilation_id BIGINT NOT NULL,
    event_id BIGINT NOT NULL,
    FOREIGN KEY (compilation_id) REFERENCES compilations (id),
    CONSTRAINT unique_compilation_event UNIQUE (compilation_id, event_id)
);

CREATE TABLE IF NOT EXISTS comments
(
    id       BIGINT      NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id  BIGINT      NOT NULL,
    event_id BIGINT      NOT NULL,
    text     VARCHAR(255) NOT NULL,
    created  TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    status   VARCHAR(15) NOT NULL
-- CONSTRAINT unique_user_event UNIQUE (user_id, event_id)
-- Запрещает вторые комментарии, пока не уверен, что это надо запрещать
);