server:
  port: 8080

spring:
  application:
    name: gateway-server

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true

      routes:
        - id: user_service_route
          uri: lb://user-service
          predicates:
            - Path=/admin/users/**

        - id: main_service_route
          uri: lb://main-service
          predicates:
            - Path=/**

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.web.reactive: DEBUG
    org.springframework.http.server.reactive: DEBUG
    org.springframework.web.reactive.function.client.ExchangeFunctions: DEBUG
    reactor.netty.http.client: DEBUG
    reactor.netty.http.server: DEBUG